// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id: 'eu-west-1:c43b548d-6eae-4a69-ace0-89ca9f9c2876',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_JwXBJvzJt',
  aws_user_pools_web_client_id: '2jq3vic77sbkna79smar1srkqi',
  oauth: {
    domain: 'leaf20c36051-20c36051-prod.auth.eu-west-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn: 'http://localhost:8080/,https://leaf.materiajs.com/',
    redirectSignOut: 'http://localhost:8080/,https://leaf.materiajs.com/',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_appsync_graphqlEndpoint: 'https://7eyhreqr5nhhvjegjk2o2yej6q.appsync-api.eu-west-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-west-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};


export default awsmobile;
